//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clasificaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clasificaciones()
        {
            this.Clientes = new HashSet<Clientes>();
        }
        [Display(Name = "Id Clasificación")]
        public int idClasificacionPK { get; set; }
        [Display(Name = "Clasificación")]
        public string descripcionClasificacion { get; set; }
        [Display(Name = "Usuario Crea")]
        public Nullable<int> idUsuarioCreaClasificacionFK { get; set; }
        [Display(Name = "Fecha Creación")]
        public Nullable<System.DateTime> fechaCreaClasificacion { get; set; }
        public Nullable<int> idUsuarioModificaClasificacionFK { get; set; }
        [Display(Name = "Fecha Modificación")]
        public Nullable<System.DateTime> fechaModificaClasificacion { get; set; }

        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
    }
}
