//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.VentaPaquetes = new HashSet<VentaPaquetes>();
        }

        [Display(Name = "Id Cliente")]
        public int idClientePK { get; set; }
        [Display(Name = "Cliente")]
        public string descripcionCliente { get; set; }
        public Nullable<int> idClasificacionClienteFK { get; set; }
        public Nullable<int> idUsuarioCreaClienteFK { get; set; }
        [Display(Name = "Fecha Creación")]
        public Nullable<System.DateTime> fechaCreaCliente { get; set; }
        public Nullable<int> idUsuarioModificaClienteFK { get; set; }
        [Display(Name = "Fecha Modificación")]
        public Nullable<System.DateTime> fechaModificaCliente { get; set; }
    
        public virtual Clasificaciones Clasificaciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaPaquetes> VentaPaquetes { get; set; }
    }
}
