//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Convenios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Convenios()
        {
            this.Vehiculos = new HashSet<Vehiculos>();
        }

        [Display(Name = "Id Convenio")]
        public int idConvenioPK { get; set; }
        [Display(Name = "Convenio")]
        public string descripcionConvenio { get; set; }
        public Nullable<int> idUsuarioCreaConvenioFK { get; set; }
        [Display(Name = "Fecha Creación")]
        public Nullable<System.DateTime> fechaCreaConvenio { get; set; }
        public Nullable<int> idUsuarioModificaConvenioFK { get; set; }
        [Display(Name = "Fecha Modificación")]
        public Nullable<System.DateTime> fechaModificaConvenio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculos> Vehiculos { get; set; }
    }
}
