//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Paquetes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paquetes()
        {
            this.VentaPaquetes = new HashSet<VentaPaquetes>();
        }

        [Display(Name = "Id Paquete")]
        public int idPaquetePK { get; set; }
        [Display(Name = "Paquete")]
        public string descripcionPaquete { get; set; }
        public Nullable<int> idFinancieraFK { get; set; }
        public Nullable<int> idVehiculoFK { get; set; }
        [Display(Name = "Monto Sugerido")]
        public Nullable<decimal> montoSugeridoPaquete { get; set; }
        [Display(Name = "Meses Sugeridos")]
        public Nullable<double> mesesSugeridoPaquete { get; set; }
        [Display(Name = "Intereses Sugeridos")]
        public Nullable<double> interesesSugeridoPaquete { get; set; }
        [Display(Name = "Cuota Mensual Estimada")]
        public Nullable<decimal> cuotaMensualEstimadaPaquete { get; set; }
        [Display(Name = "Cláusulas")]
        public string clausulasPaquete { get; set; }
        public Nullable<int> idUsuarioCreaPaqueteFK { get; set; }
        [Display(Name = "Fecha Creación")]
        public Nullable<System.DateTime> fechaCreaPaquete { get; set; }
        public Nullable<int> idUsuarioModificaPaqueteFK { get; set; }
        [Display(Name = "Fecha Modificación")]
        public Nullable<System.DateTime> fechaModificaPaquete { get; set; }
    
        public virtual Financieras Financieras { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaPaquetes> VentaPaquetes { get; set; }
    }
}
