//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Perfiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Perfiles()
        {
            this.Usuarios2 = new HashSet<Usuarios>();
        }

        [Display(Name = "Id Perfil")]
        public int idPerfilPK { get; set; }
        [Display(Name = "Perfil")]
        public string descripcionPerfil { get; set; }
        public Nullable<int> idUsuarioCreaPerfilFK { get; set; }
        [Display(Name = "Fecha Creación")]
        public Nullable<System.DateTime> fechaCreaPerfil { get; set; }
        public Nullable<int> idUsuarioModificaPerfilFK { get; set; }
        [Display(Name = "Fecha Modificación")]
        public Nullable<System.DateTime> fechaModificaPerfil { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios2 { get; set; }
    }
}
