//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Clasificaciones = new HashSet<Clasificaciones>();
            this.Clasificaciones1 = new HashSet<Clasificaciones>();
            this.Clientes = new HashSet<Clientes>();
            this.Clientes1 = new HashSet<Clientes>();
            this.Financieras = new HashSet<Financieras>();
            this.Financieras1 = new HashSet<Financieras>();
            this.Paquetes = new HashSet<Paquetes>();
            this.Paquetes1 = new HashSet<Paquetes>();
            this.Perfiles = new HashSet<Perfiles>();
            this.Perfiles1 = new HashSet<Perfiles>();
            this.Usuarios1 = new HashSet<Usuarios>();
            this.Usuarios11 = new HashSet<Usuarios>();
            this.Vehiculos = new HashSet<Vehiculos>();
            this.Vehiculos1 = new HashSet<Vehiculos>();
            this.VentaPaquetes = new HashSet<VentaPaquetes>();
            this.VentaPaquetes1 = new HashSet<VentaPaquetes>();
        }

        [Display(Name = "Id Usuario")]
        public int idUsuarioPK { get; set; }
        [Display(Name = "Usuario")]
        public string descripcionUsuario { get; set; }
        public Nullable<int> idUsuarioCreaUsuarioFK { get; set; }
        [Display(Name = "Fecha Creación")]
        public Nullable<System.DateTime> fechaCreaUsuario { get; set; }
        public Nullable<int> idUsuarioModificaUsuarioFK { get; set; }
        [Display(Name = "Fecha Modificación")]
        public Nullable<System.DateTime> fechaModificaUsuario { get; set; }
        public Nullable<int> idPerfilUsuarioFK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clasificaciones> Clasificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clasificaciones> Clasificaciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financieras> Financieras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financieras> Financieras1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paquetes> Paquetes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paquetes> Paquetes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perfiles> Perfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perfiles> Perfiles1 { get; set; }
        public virtual Perfiles Perfiles2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios11 { get; set; }
        public virtual Usuarios Usuarios3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculos> Vehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculos> Vehiculos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaPaquetes> VentaPaquetes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaPaquetes> VentaPaquetes1 { get; set; }
    }
}
