//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculos()
        {
            this.Paquetes = new HashSet<Paquetes>();
        }

        [Display(Name = "Id Vehículo")]
        public int idVehiculoPK { get; set; }
        [Display(Name = "Vehículo")]
        public string descripcionVehiculo { get; set; }
        [Display(Name = "Matrícula")]
        public string matriculaVehiculo { get; set; }
        public Nullable<int> idConvenioFK { get; set; }
        public Nullable<int> idUsuarioCreaVehiculoFK { get; set; }
        [Display(Name = "Fecha Creación")]
        public Nullable<System.DateTime> fechaCreaVehiculo { get; set; }
        public Nullable<int> idUsuarioModificaVehiculoFK { get; set; }
        [Display(Name = "Fecha Modificación")]
        public Nullable<System.DateTime> fechaModificaVehiculo { get; set; }
    
        public virtual Convenios Convenios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paquetes> Paquetes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
