//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VentaPaquetes
    {
        [Display(Name = "Id Venta de Paquete")]
        public int idVentaPaquetePK { get; set; }
        [Display(Name = "Número de Venta de Paquete")]
        public Nullable<int> numeroVentaPaquete { get; set; }
        public Nullable<int> idClienteFK { get; set; }
        public Nullable<int> idPaqueteFK { get; set; }
        public Nullable<int> idUsuarioCreaVentaPaqueteFK { get; set; }
        [Display(Name = "Fecha Creación")]
        public Nullable<System.DateTime> fechaCreaVentaPaquete { get; set; }
        public Nullable<int> idUsuarioModificaVentaPaqueteFK { get; set; }
        [Display(Name = "Fecha Modificación")]
        public Nullable<System.DateTime> fechaModificaVentaPaquete { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Paquetes Paquetes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
